FROM eclipse-temurin:21-jdk

WORKDIR /app

# Copy Maven wrapper files
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# Download dependencies
RUN ./mvnw dependency:go-offline

# Copy source code
COPY src ./src

# Expose application and debug ports
EXPOSE 8080
EXPOSE 5005

# Run application with debug enabled
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=docker", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]
